/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author lucky13
 */
public class InputPanel extends javax.swing.JPanel {

    /**
     * Creates new form InputPanel
     */
    public InputPanel(javax.swing.JPanel topLevelPane) {
        this.topLevelPane = topLevelPane;
        initComponents();
        prefferedX = getPreferredSize().width - (getPreferredSize().width/2);
        prefferedY = getPreferredSize().height;
    }

    public int[] getPrefferedCoords() {
        int[] coords = {prefferedX, prefferedY};
        return coords;
    }
    
    public void setCurrentTextField(javax.swing.JTextField textField) {
        this.currentTextField = textField;
    }
    
    public void setNextFrame(javax.swing.JPanel next) {
        this.nextFrame = next;
    }
    
    public void setOkBtnAction (javax.swing.Action a) {
        btnOK.setAction(a);
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExt = new javax.swing.JButton();
        btnEra = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnHype = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 0, 0), null));
        setPreferredSize(new java.awt.Dimension(360, 360));
        setLayout(null);

        btnExt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnBck.png"))); // NOI18N
        btnExt.setBorderPainted(false);
        btnExt.setContentAreaFilled(false);
        btnExt.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnExt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExt.setIconTextGap(0);
        btnExt.setName("6"); // NOI18N
        btnExt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnBck.png"))); // NOI18N
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });
        add(btnExt);
        btnExt.setBounds(270, 0, 90, 90);

        btnEra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnEra.png"))); // NOI18N
        btnEra.setBorderPainted(false);
        btnEra.setContentAreaFilled(false);
        btnEra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEra.setIconTextGap(0);
        btnEra.setName("6"); // NOI18N
        btnEra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnEra.png"))); // NOI18N
        btnEra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraActionPerformed(evt);
            }
        });
        add(btnEra);
        btnEra.setBounds(270, 90, 90, 90);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnOk.png"))); // NOI18N
        btnOK.setBorderPainted(false);
        btnOK.setContentAreaFilled(false);
        btnOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK.setIconTextGap(0);
        btnOK.setName("1"); // NOI18N
        btnOK.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnOk.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        add(btnOK);
        btnOK.setBounds(270, 180, 90, 180);

        btnHype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnHype.png"))); // NOI18N
        btnHype.setBorderPainted(false);
        btnHype.setContentAreaFilled(false);
        btnHype.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHype.setIconTextGap(0);
        btnHype.setName("-"); // NOI18N
        btnHype.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnHype.png"))); // NOI18N
        btnHype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypeActionPerformed(evt);
            }
        });
        add(btnHype);
        btnHype.setBounds(180, 270, 90, 90);

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn0.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setIconTextGap(0);
        btn0.setName("0"); // NOI18N
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn0.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        add(btn0);
        btn0.setBounds(0, 270, 180, 90);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn1.png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setIconTextGap(0);
        btn1.setName("1"); // NOI18N
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn1.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        add(btn1);
        btn1.setBounds(0, 180, 90, 90);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn2.png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setIconTextGap(0);
        btn2.setName("2"); // NOI18N
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn2.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        add(btn2);
        btn2.setBounds(90, 180, 90, 90);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn3.png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setIconTextGap(0);
        btn3.setName("3"); // NOI18N
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn3.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        add(btn3);
        btn3.setBounds(180, 180, 90, 90);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn4.png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setIconTextGap(0);
        btn4.setName("4"); // NOI18N
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn4.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        add(btn4);
        btn4.setBounds(0, 90, 90, 90);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn5.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setIconTextGap(0);
        btn5.setName("5"); // NOI18N
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn5.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        add(btn5);
        btn5.setBounds(90, 90, 90, 90);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn6.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setIconTextGap(0);
        btn6.setName("6"); // NOI18N
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn6.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        add(btn6);
        btn6.setBounds(180, 90, 90, 90);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn7.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setIconTextGap(0);
        btn7.setName("7"); // NOI18N
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn7.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        add(btn7);
        btn7.setBounds(0, 0, 90, 90);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn8.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setIconTextGap(0);
        btn8.setName("8"); // NOI18N
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn8.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        add(btn8);
        btn8.setBounds(90, 0, 90, 90);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn9.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setIconTextGap(0);
        btn9.setName("9"); // NOI18N
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn9.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        add(btn9);
        btn9.setBounds(180, 0, 90, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn1.getName());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn0.getName());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn2.getName());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn3.getName());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn4.getName());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn5.getName());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn6.getName());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn7.getName());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn8.getName());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btn9.getName());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnHypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypeActionPerformed
        // TODO add your handling code here:
        currentTextField.setText(currentTextField.getText() + btnHype.getName());
    }//GEN-LAST:event_btnHypeActionPerformed

    private void btnEraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraActionPerformed
        // TODO add your handling code here:
        String txt = currentTextField.getText();
        if (txt.length() > 0) {
            currentTextField.setText(txt.substring(0, txt.length() - 1));
        }
    }//GEN-LAST:event_btnEraActionPerformed

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        // TODO add your handling code here:
//        classes.MainApp.switchFrames(topLevelPane,classes.MainApp.transacWin);
    }//GEN-LAST:event_btnExtActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
//        MainApp.switchFrames(topLevelPane, nextFrame);
//        MainApp.loggedIn = topLevelPane instanceof classes.LogIn ? true : MainApp.loggedIn;
    }//GEN-LAST:event_btnOKActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnEra;
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnHype;
    private javax.swing.JButton btnOK;
    // End of variables declaration//GEN-END:variables
    private int prefferedX, prefferedY;
    private javax.swing.JPanel topLevelPane;
    private javax.swing.JPanel nextFrame;
    private javax.swing.JTextField currentTextField;
}
