/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes;

/**
 *
 * @author lucky13
 */
public class ChangePinFrame extends javax.swing.JPanel {

    /**
     * Creates new form ChangePinFrame
     */
    public ChangePinFrame(MainApp mn) {
        initComponents();
        this.app = mn;
    }

    private void buttonPress(String text) {
        String txt = currentTextField.getText() + text;
        if (currentTextField != null) {
            if (text.equals("")) {
                if (txt.length() > 0) {
                    currentTextField.setText(txt.substring(0, txt.length() - 1));
                }
            } else {
                if (txt.length() > 6) {
                    txt = txt.substring(0, txt.length() - 1);
                }
                currentTextField.setText(txt);            
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        cnfLbl = new javax.swing.JLabel();
        newPinLbl = new javax.swing.JLabel();
        confirmTF = new javax.swing.JTextField();
        newPinTF = new javax.swing.JTextField();
        dialPad = new javax.swing.JPanel();
        btnExt2 = new javax.swing.JButton();
        btnEra = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnHype = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PIN/header.gif"))); // NOI18N
        header.setFocusable(false);
        header.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(header);
        header.setBounds(50, 10, 590, 128);

        cnfLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cnfLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PIN/Confirm.png"))); // NOI18N
        cnfLbl.setFocusable(false);
        cnfLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(cnfLbl);
        cnfLbl.setBounds(120, 230, 170, 70);

        newPinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPinLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PIN/NewPin.png"))); // NOI18N
        newPinLbl.setFocusable(false);
        newPinLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(newPinLbl);
        newPinLbl.setBounds(120, 150, 170, 70);

        confirmTF.setEditable(false);
        confirmTF.setBackground(new java.awt.Color(212, 118, 107));
        confirmTF.setFont(new java.awt.Font("JetBrainsMonoNL NF Medium", 1, 24)); // NOI18N
        confirmTF.setForeground(new java.awt.Color(96, 28, 28));
        confirmTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(96, 28, 28), null));
        confirmTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        confirmTF.setSelectedTextColor(new java.awt.Color(212, 118, 107));
        confirmTF.setSelectionColor(new java.awt.Color(172, 50, 50));
        confirmTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmTFFocusGained(evt);
            }
        });
        add(confirmTF);
        confirmTF.setBounds(300, 240, 280, 50);

        newPinTF.setEditable(false);
        newPinTF.setBackground(new java.awt.Color(212, 118, 107));
        newPinTF.setFont(new java.awt.Font("JetBrainsMonoNL NF Medium", 1, 24)); // NOI18N
        newPinTF.setForeground(new java.awt.Color(96, 28, 28));
        newPinTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(96, 28, 28), null));
        newPinTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        newPinTF.setSelectedTextColor(new java.awt.Color(212, 118, 107));
        newPinTF.setSelectionColor(new java.awt.Color(172, 50, 50));
        newPinTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPinTFFocusGained(evt);
            }
        });
        add(newPinTF);
        newPinTF.setBounds(300, 160, 280, 50);

        dialPad.setBackground(new java.awt.Color(255, 102, 102));
        dialPad.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 0, 0), null));
        dialPad.setFocusable(false);
        dialPad.setPreferredSize(new java.awt.Dimension(360, 360));
        dialPad.setLayout(null);

        btnExt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnBck.png"))); // NOI18N
        btnExt2.setBorderPainted(false);
        btnExt2.setContentAreaFilled(false);
        btnExt2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnExt2.setFocusable(false);
        btnExt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExt2.setIconTextGap(0);
        btnExt2.setName("6"); // NOI18N
        btnExt2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnBck.png"))); // NOI18N
        btnExt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExt2ActionPerformed(evt);
            }
        });
        dialPad.add(btnExt2);
        btnExt2.setBounds(270, 0, 90, 90);

        btnEra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnEra.png"))); // NOI18N
        btnEra.setBorderPainted(false);
        btnEra.setContentAreaFilled(false);
        btnEra.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnEra.setFocusable(false);
        btnEra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEra.setIconTextGap(0);
        btnEra.setName("6"); // NOI18N
        btnEra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnEra.png"))); // NOI18N
        btnEra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraActionPerformed(evt);
            }
        });
        dialPad.add(btnEra);
        btnEra.setBounds(270, 90, 90, 90);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnOk.png"))); // NOI18N
        btnOK.setBorderPainted(false);
        btnOK.setContentAreaFilled(false);
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnOK.setFocusable(false);
        btnOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK.setIconTextGap(0);
        btnOK.setName("1"); // NOI18N
        btnOK.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnOk.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        dialPad.add(btnOK);
        btnOK.setBounds(270, 180, 90, 180);

        btnHype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/BtnDot.png"))); // NOI18N
        btnHype.setBorderPainted(false);
        btnHype.setContentAreaFilled(false);
        btnHype.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnHype.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/disabled/Buttons.png"))); // NOI18N
        btnHype.setEnabled(false);
        btnHype.setFocusable(false);
        btnHype.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHype.setIconTextGap(0);
        btnHype.setName("."); // NOI18N
        btnHype.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/BtnDot.png"))); // NOI18N
        btnHype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypeActionPerformed(evt);
            }
        });
        dialPad.add(btnHype);
        btnHype.setBounds(180, 270, 90, 90);

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn0.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn0.setFocusable(false);
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setIconTextGap(0);
        btn0.setName("0"); // NOI18N
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn0.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        dialPad.add(btn0);
        btn0.setBounds(0, 270, 180, 90);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn1.png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn1.setFocusable(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setIconTextGap(0);
        btn1.setName("1"); // NOI18N
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn1.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        dialPad.add(btn1);
        btn1.setBounds(0, 180, 90, 90);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn2.png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn2.setFocusable(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setIconTextGap(0);
        btn2.setName("2"); // NOI18N
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn2.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        dialPad.add(btn2);
        btn2.setBounds(90, 180, 90, 90);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn3.png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn3.setFocusable(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setIconTextGap(0);
        btn3.setName("3"); // NOI18N
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn3.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        dialPad.add(btn3);
        btn3.setBounds(180, 180, 90, 90);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn4.png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn4.setFocusable(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setIconTextGap(0);
        btn4.setName("4"); // NOI18N
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn4.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        dialPad.add(btn4);
        btn4.setBounds(0, 90, 90, 90);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn5.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn5.setFocusable(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setIconTextGap(0);
        btn5.setName("5"); // NOI18N
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn5.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        dialPad.add(btn5);
        btn5.setBounds(90, 90, 90, 90);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn6.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn6.setFocusable(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setIconTextGap(0);
        btn6.setName("6"); // NOI18N
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn6.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        dialPad.add(btn6);
        btn6.setBounds(180, 90, 90, 90);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn7.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn7.setFocusable(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setIconTextGap(0);
        btn7.setName("7"); // NOI18N
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn7.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        dialPad.add(btn7);
        btn7.setBounds(0, 0, 90, 90);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn8.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn8.setFocusable(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setIconTextGap(0);
        btn8.setName("8"); // NOI18N
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn8.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        dialPad.add(btn8);
        btn8.setBounds(90, 0, 90, 90);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/default/Btn9.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btn9.setFocusable(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setIconTextGap(0);
        btn9.setName("9"); // NOI18N
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Buttons/clicked/Btn9.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        dialPad.add(btn9);
        btn9.setBounds(180, 0, 90, 90);

        add(dialPad);
        dialPad.setBounds(170, 310, 360, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmTFFocusGained
        // TODO add your handling code here:
        currentTextField = confirmTF;
        confirmTF.setBorder(this.app.etchedRaised);
        newPinTF.setBorder(this.app.defaultBorder);
    }//GEN-LAST:event_confirmTFFocusGained

    private void newPinTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPinTFFocusGained
        // TODO add your handling code here:
        currentTextField = newPinTF;
        newPinTF.setBorder(this.app.etchedRaised);
        confirmTF.setBorder(this.app.defaultBorder);
    }//GEN-LAST:event_newPinTFFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        newPinTF.grabFocus();
    }//GEN-LAST:event_formComponentShown

    private void btnExt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExt2ActionPerformed
        // TODO add your handling code here:
        this.app.switchFrames(this,this.app.transacWin);
    }//GEN-LAST:event_btnExt2ActionPerformed

    private void btnEraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraActionPerformed
        // TODO add your handling code here:
        this.buttonPress("");
    }//GEN-LAST:event_btnEraActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        String newPin = newPinTF.getText();
        if (newPin.equals(confirmTF.getText())) {
            this.app.setPin(newPin);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnHypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHypeActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn0.getName());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn1.getName());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn2.getName());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn3.getName());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn4.getName());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn5.getName());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn6.getName());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn7.getName());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn8.getName());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        this.buttonPress(btn9.getName());
    }//GEN-LAST:event_btn9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnEra;
    private javax.swing.JButton btnExt2;
    private javax.swing.JButton btnHype;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel cnfLbl;
    private javax.swing.JTextField confirmTF;
    private javax.swing.JPanel dialPad;
    private javax.swing.JLabel header;
    private javax.swing.JLabel newPinLbl;
    private javax.swing.JTextField newPinTF;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextField currentTextField;
    MainApp app;
}