/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes;

/**
 *
 * @author lucky13
 */
public class CheckBalFrame extends javax.swing.JPanel {

    /**
     * Creates new form CheckBalWindow
     */
    public CheckBalFrame(MainApp mn) {
        initComponents();
        this.app = mn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        bck = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Check Bal/amnt.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(0);
        add(jLabel2);
        jLabel2.setBounds(275, 290, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Check Bal/header.gif"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);
        add(jLabel1);
        jLabel1.setBounds(60, 20, 570, 96);

        balanceTF.setEditable(false);
        balanceTF.setBackground(new java.awt.Color(212, 118, 107));
        balanceTF.setFont(new java.awt.Font("JetBrainsMonoNL NF Medium", 1, 24)); // NOI18N
        balanceTF.setForeground(new java.awt.Color(96, 28, 28));
        balanceTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        balanceTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(96, 28, 28), null));
        balanceTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        balanceTF.setFocusable(false);
        balanceTF.setHighlighter(null);
        balanceTF.setSelectedTextColor(new java.awt.Color(212, 118, 107));
        balanceTF.setSelectionColor(new java.awt.Color(172, 50, 50));
        add(balanceTF);
        balanceTF.setBounds(210, 330, 280, 50);

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/Default.png"))); // NOI18N
        bck.setBorderPainted(false);
        bck.setContentAreaFilled(false);
        bck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bck.setIconTextGap(0);
        bck.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/Pressed.png"))); // NOI18N
        bck.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/RollOver.gif"))); // NOI18N
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        add(bck);
        bck.setBounds(10, 640, 150, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        balanceTF.setText(String.format("%.2f", this.app.getBalance()));
    }//GEN-LAST:event_formComponentShown

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        // TODO add your handling code here:
        this.app.switchFrames(this, this.app.transacWin);
    }//GEN-LAST:event_bckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTF;
    private javax.swing.JButton bck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    MainApp app;
}