/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes;

/**
 *
 * @author lucky13
 */
public class FastCashFrame extends javax.swing.JPanel {

    /**
     * Creates new form FastCashFrame
     */
    public FastCashFrame(MainApp mn) {
        initComponents();
        this.app = mn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by         this.app.deduceBalance(Double.parseDouble(btn1500.getName()));
the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn1500 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn2500 = new javax.swing.JButton();
        btn3000 = new javax.swing.JButton();
        btn3500 = new javax.swing.JButton();
        bck = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/header.gif"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);
        add(jLabel1);
        jLabel1.setBounds(30, 50, 640, 100);

        btn100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices1.png"))); // NOI18N
        btn100.setBorderPainted(false);
        btn100.setContentAreaFilled(false);
        btn100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn100.setIconTextGap(0);
        btn100.setName("100"); // NOI18N
        btn100.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)1.png"))); // NOI18N
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        add(btn100);
        btn100.setBounds(30, 200, 290, 90);

        btn500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices2.png"))); // NOI18N
        btn500.setBorderPainted(false);
        btn500.setContentAreaFilled(false);
        btn500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn500.setIconTextGap(0);
        btn500.setName("500"); // NOI18N
        btn500.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)2.png"))); // NOI18N
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        add(btn500);
        btn500.setBounds(380, 200, 290, 90);

        btn1000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices3.png"))); // NOI18N
        btn1000.setBorderPainted(false);
        btn1000.setContentAreaFilled(false);
        btn1000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1000.setIconTextGap(0);
        btn1000.setName("1000"); // NOI18N
        btn1000.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)3.png"))); // NOI18N
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });
        add(btn1000);
        btn1000.setBounds(30, 300, 290, 90);

        btn1500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices4.png"))); // NOI18N
        btn1500.setBorderPainted(false);
        btn1500.setContentAreaFilled(false);
        btn1500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1500.setIconTextGap(0);
        btn1500.setName("1500"); // NOI18N
        btn1500.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)4.png"))); // NOI18N
        btn1500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1500ActionPerformed(evt);
            }
        });
        add(btn1500);
        btn1500.setBounds(380, 300, 290, 90);

        btn2000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices5.png"))); // NOI18N
        btn2000.setBorderPainted(false);
        btn2000.setContentAreaFilled(false);
        btn2000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2000.setIconTextGap(0);
        btn2000.setName("2000"); // NOI18N
        btn2000.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)5.png"))); // NOI18N
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });
        add(btn2000);
        btn2000.setBounds(30, 400, 290, 90);

        btn2500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices6.png"))); // NOI18N
        btn2500.setBorderPainted(false);
        btn2500.setContentAreaFilled(false);
        btn2500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2500.setIconTextGap(0);
        btn2500.setName("2500"); // NOI18N
        btn2500.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)6.png"))); // NOI18N
        btn2500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2500ActionPerformed(evt);
            }
        });
        add(btn2500);
        btn2500.setBounds(380, 400, 290, 90);

        btn3000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices7.png"))); // NOI18N
        btn3000.setBorderPainted(false);
        btn3000.setContentAreaFilled(false);
        btn3000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3000.setIconTextGap(0);
        btn3000.setName("3000"); // NOI18N
        btn3000.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)7.png"))); // NOI18N
        btn3000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3000ActionPerformed(evt);
            }
        });
        add(btn3000);
        btn3000.setBounds(30, 500, 290, 90);

        btn3500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices8.png"))); // NOI18N
        btn3500.setBorderPainted(false);
        btn3500.setContentAreaFilled(false);
        btn3500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3500.setIconTextGap(0);
        btn3500.setName("3500"); // NOI18N
        btn3500.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FastCash/Choices(Pressed)8.png"))); // NOI18N
        btn3500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3500ActionPerformed(evt);
            }
        });
        add(btn3500);
        btn3500.setBounds(380, 500, 290, 90);

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/Default.png"))); // NOI18N
        bck.setBorderPainted(false);
        bck.setContentAreaFilled(false);
        bck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bck.setIconTextGap(0);
        bck.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/Pressed.png"))); // NOI18N
        bck.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back/RollOver.gif"))); // NOI18N
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        add(bck);
        bck.setBounds(10, 644, 150, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn500.getName()));
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn3500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3500ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn3500.getName()));
    }//GEN-LAST:event_btn3500ActionPerformed

    private void btn2500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2500ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn2500.getName()));
    }//GEN-LAST:event_btn2500ActionPerformed

    private void btn1500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1500ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn1500.getName()));
    }//GEN-LAST:event_btn1500ActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        // TODO add your handling code here:
        this.app.switchFrames(this, this.app.transacWin);
    }//GEN-LAST:event_bckActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn100.getName()));
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn1000.getName()));
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn2000.getName()));
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn3000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3000ActionPerformed
        // TODO add your handling code here:
        this.app.deduceBalance(Double.parseDouble(btn3000.getName()));
    }//GEN-LAST:event_btn3000ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn1500;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn2500;
    private javax.swing.JButton btn3000;
    private javax.swing.JButton btn3500;
    private javax.swing.JButton btn500;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    MainApp app;
}