/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes;

/**
 *
 * @author lucky13
 */
public class IntroductionWindow extends javax.swing.JPanel {

    /**
     * Creates new form FirstWindow
     */
    
    public IntroductionWindow(MainApp mn) {
        initComponents();
        this.app = mn;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this -method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 172, 111));
        setPreferredSize(new java.awt.Dimension(700, 700));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Tap.gif"))); // NOI18N
        jLabel1.setIconTextGap(0);
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        add(jLabel1);
        jLabel1.setBounds(90, 380, 470, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/welcome.gif"))); // NOI18N
        jLabel2.setIconTextGap(0);
        add(jLabel2);
        jLabel2.setBounds(30, 220, 620, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N
        jLabel3.setIconTextGap(0);
        add(jLabel3);
        jLabel3.setBounds(570, 0, 130, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        this.app.switchFrames(this.app.introWin, this.app.transacWin);
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    MainApp app;
}
