/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author lucky13
 */
public class MainApp extends javax.swing.JFrame {
    private boolean loggedIn = false;
    private String accNum="1234", pin="0000";
    private double balance = 123.65f;
    Border etchedRaised = BorderFactory.createEtchedBorder(1, new Color(96,28,28), new Color(30,240,30));
    Border defaultBorder = BorderFactory.createEtchedBorder(0, new Color(96,28,28), null);

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        initFrames();
    }
    
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String num){
        this.pin = num;
    }
    
    public String getAccNum(){
        return this.accNum;
    }

    public void setAccNum(String num){
        this.accNum = num;
    }

    public double getBalance(){
        return this.balance;
    }
    
    public void setBalance(double bal){
        this.balance = bal;
    }
    
    public void logIn() {
        this.loggedIn = true;
    }
    
    public boolean isLoggedIn() {
        return this.loggedIn;
    }
    
    public void switchFrames(javax.swing.JPanel firstFrame, javax.swing.JPanel secondFrame) {
        if (secondFrame != null) {
            firstFrame.setVisible(false);        
            secondFrame.setVisible(true);

            for (java.awt.Component comp : firstFrame.getComponents()) {
                if (comp instanceof javax.swing.JTextField) {
                    ((javax.swing.JTextField) comp).setText("");
                }
            }
        }
    };
    
    public void addBalance(double val) {
        this.setBalance(this.getBalance() +  val);
        JOptionPane.showMessageDialog(this, String.format(
                "Deposit Amount: %.2f Bytes\n"
                + "------------------------------------\n"
                + "Current Balance: %.2f Bytes", val, this.getBalance()),
                "Success",
                1);        
    }
    
    public void deduceBalance(double val) {
        double totalAmount = this.getBalance() -  val;
        
        if (totalAmount >= 0) {
            this.setBalance(totalAmount);
            JOptionPane.showMessageDialog(this, String.format(
                    "Withdraw Amount: %.2f Bytes\n"
                    + "------------------------------------\n"
                    + "Remaining Balance: %.2f Bytes", val, this.getBalance()),
                    "Success",
                    1);
        } else {
            JOptionPane.showMessageDialog(this,
                    "INSUFICIENT FUNDS!",
                    "Insuficient",
                    1);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(50, 172, 111));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 28, 28));
        jLabel1.setText("© Nethan Quinn G. Jael");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 680, 170, 17);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initFrames() {
        introWin = new classes.IntroductionWindow(this);
        transacWin = new classes.TransactionWindow(this);
        loginWin = new classes.LogIn(this);
        fastCashWin = new classes.FastCashFrame(this);
        checkBalWin = new classes.CheckBalFrame(this);
        withdrawWin = new classes.WithdrawFrame(this);
        depositWin = new classes.DepositFrame(this);
        changePinWin = new classes.ChangePinFrame(this);
        devInfoWin = new classes.DeveloperFrame(this);

        javax.swing.JPanel[] frames = 
        {
            loginWin, introWin, transacWin, fastCashWin, checkBalWin, 
            withdrawWin, depositWin, changePinWin, devInfoWin
        };
       
        /*Set and Add Panels to Frame*/
        for (javax.swing.JPanel frame : frames) {
            this.add(frame);
            System.out.println(frame);
            frame.setBounds(0, 0, frame.getPreferredSize().width,
                    frame.getPreferredSize().height);
            frame.setBackground(this.getBackground());
        }
        
        /*Set all Panels' Visibility except the introWin to false*/
        for (java.awt.Component comp : getContentPane().getComponents()) {
            if (comp != introWin && comp instanceof javax.swing.JPanel) {
                comp.setVisible(false);
            }
        }

        pack();
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    classes.LogIn loginWin;
    classes.IntroductionWindow introWin;
    classes.TransactionWindow transacWin;
    classes.FastCashFrame fastCashWin;
    classes.CheckBalFrame checkBalWin;
    classes.WithdrawFrame withdrawWin;
    classes.DepositFrame depositWin;
    classes.ChangePinFrame changePinWin;
    classes.DeveloperFrame devInfoWin;
}
